FROM python:3.12-slim-bookworm

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl nodejs npm libgl1-mesa-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV HOME /root
ENV RYE_HOME ${HOME}/.rye

WORKDIR $HOME

COPY . $HOME

RUN bash ./build.sh
SHELL ["bash", "-l", "-c"]
ENTRYPOINT [ "bash", "-l", "-c" ]
EXPOSE 8888
CMD ["bash -l run.sh"]
